#include <iostream>
#include <cstdlib>
#include <ctime>
#include <string>
#include <vector>
using namespace std;


int _tmain(int argc, _TCHAR* argv[])
{
	Declare variables
        int players;
        int turn = 1;
        vector<string> names;
        string playerName;
        int dice[5];
        int finalScore = 0;
        char reroll[5];
        char rollDice;
        int tries = 1;
        const int DICE = 5;
        int roll[DICE];
        int scorecard;
        int scoreThisTurn(int scorecard);
        int turnScore = 0;
        //Introduction, get number of players.
        cout << "Hello, welcome to Yahtzee!  How many players are there?" ;
        cin >> players;
        if (players > 4) {
 	       cout << "Sorry, the maximum number of players is 4." << endl;
               cout << "How many players are there?" << endl;
               cin >> player;
        }
        //Get player names
        string getNames();
        for (int i = 0; i < players; i++)  {
	        cout << "Hello player " << i + 1 << ", please enter your name" << endl;
                cin >> playerName;
                names.push_back(playerName);
        }
        srand(time(NULL));  //random seed
        cout << "Welcome to Yahtzee!\n";
        while (turn <= 13) {       //roll dice
        cout << "Press 'r' to roll" << endl;
        cin >> rollDice;
        if (rollDice == 'r') {
		for (int i = 0; i < DICE; i++) {
			roll[i] = rand() % 6 + 1;
                }
        }
        cout << "You rolled: " << roll[0] << ", " << roll[1] << ", " <<
        roll[2] << ", " << roll[3] << ", " << roll[4] << endl;
        cout << "Type y to reroll or n to keep.  For example yynnn would keep the first three dice" << endl;
        cin >> reroll[0] >> reroll[1] >> reroll[2] >> reroll[3] >> reroll[4];
        for (int i = 0; i < DICE; i++) {
  		if (reroll[i] == 'y') {
        		roll[i] = rand() % 6 + 1;
                } 
	        else if (reroll[i] == 'n') {
                     	roll[i];
                     }
                	else cout << "Sorry you entered an invalid letter." << endl;
        }
        cout << "Your second roll is: " << roll[0] << ", " << roll[1] << ", " <<
        roll[2] << ", " << roll[3] << ", " << roll[4] << endl;
        cout << "Type y to reroll or n to keep.  For example yynnn would keep the first three dice" << endl;
        cin >> reroll[0] >> reroll[1] >> reroll[2] >> reroll[3] >> reroll[4];
        for (int i = 0; i < DICE; i++) {
    		if (reroll[i] == 'y') {
    	        	roll[i] = rand() % 6 + 1;
                }
                else if (reroll[i] == 'n') {
                	roll[i];
                        }
                        else cout << "Sorry you entered an invalid letter." << endl;
        }
        cout << "Your third roll is: " << roll[0] << ", " << roll[1] << ", " << roll[2] << ", " << roll[3] << ", " << roll[4] << endl;
       //displays scorecard categories
	coutt << "Which category would you like to score this in" << endl;
        cout << "1 - ones: " << endl;
        cout << "2 - twos: " << endl;
        cout << "3 - threes: " << endl;
        cout << "4 - fours: " << endl;
        cout << "5 - fives: " << endl;
        cout << "6 - sixes: " << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "7 - 3 of a kind: " << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cout << "8 - 4 of a kind: " << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "9 - small straight: " << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cout << "10 - large straight: " << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "11 - full house: " << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cout << "12 - yahtzee: " << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "13 - chance: " << endl;
    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //asks player to choose where to score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "\nEnter 1-14 to choose a category." << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cin >> scorecard;
    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //assigns points
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < DICE; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            turnScore = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (scorecard == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (roll[i] == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            turnScore = turnScore + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (scorecard == 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (roll[i] == 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        turnScore = turnScore + 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (scorecard == 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (roll[i] == 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    turnScore = turnScore + 3;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (scorecard == 4) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (roll[i] == 4) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                turnScore = turnScore + 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (scorecard == 5) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (roll[i] == 5) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            turnScore = turnScore + 5;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (scorecard == 6) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (roll[i] == 6) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        turnScore = turnScore + 6;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (scorecard == 7) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (roll[i] == 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    turnScore = turnScore + 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << scorecard << endl;
    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                turn++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
   
    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      system("pause");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 0;
