CXX = g++
SRCS = Actor.cpp Hero.cpp Floor.cpp Maze.cpp Wombat.cpp main.cpp
HEADERS = Actor.hpp Hero.hpp Floor.hpp Maze.hpp Wombat.hpp

maze: ${SRCS} ${HEADERS}
	${CXX} ${SRCS} -o maze
clean:
	rm -f *.o maze
